#!/usr/bin/bash

xrandr --output eDP-1 --brightness $( echo "$( xrandr --current --verbose | grep -i -m $( xrandr --current | grep ' connected' | awk '{print $1}' | grep -ne 'eDP-1' | cut -f1 -d:) 'brightness' | awk '{FS=": "; print $2}')+0.1" | bc)